### ISSUE TITLE
Flow: MessageList items API

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-messages#10]
Add the following bean class to the `vaadin-messages-flow` module:
```java
class MessageListItem {
  void setText(String)
  void setTime(Instant)

  void setUserName(String)
  void setUserImage(String)
  void setUserAbbreviation(String)
  void setUserColorIndex(int)
}
```

Add the following methods to `MessageList`:
```java
void setItems(List<MessageListItem> items)
List<MessageListItem> getItems()
```

The items should be converted to the web component's `items` array.

It's not important at this point how the `Instant time` is converted to a string by default.

Update: The `items` array should also be updated when changing the properties of a `MessageListItem` that belongs to a `MessageList` at that moment (see the comments below).

**Comment by Legioth** [comment]
Did we also discuss that it would be good to immediately implement so that this would work?
```
MessageListItem item = new MessageListItem();
messageList.setItems(Arrays.asList(item));
item.setText("Foo");
```
One example on how to make this work can be found in `AvatarGroup`.

**Comment by pekam** [comment]
Thanks for reminding! Yes, let's do it like that from the beginning. For reference, [here's the PR that fixed this in AvatarGroup](https://github.com/vaadin/vaadin-avatar-flow/pull/25).

**Comment by pekam** [comment]
PR https://github.com/vaadin/vaadin-flow-components/pull/640
