### ISSUE TITLE
Flow: MessageList default time formatter

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-messages#12]
The default formatter should use `UI.getLocale()`.
```java
instant.atZone(ZoneId.systemDefault())
  .format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM, FormatStyle.SHORT)
  .withLocale(UI.getCurrent().getLocale())
```
This would use the server timezone. (The client timezone could be retrieved asynchronously with `Page::retrieveExtendedClientDetails`.)

**Comment by Legioth** [comment]
Should be noted that when using `UI.getLocale()`, then the component should also implement `com.vaadin.flow.i18n.LocaleChangeObserver` so that it can update itself when the UI locale changes.

**Comment by pekam** [comment]
We decided to implement the default formatting by using client-side code, so that we can provide the best possible default behavior by using the user's browser's time zone. Closing in favor of #25.
