### ISSUE TITLE
Define specific tag names for avatar, text area and button

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-messages#28]
As pointed out by @tomivirkki. When using an external component in another component, the convention is to define a new tag name for it.

In `vaadin-message`:
- Define `vaadin-message-avatar` and use it instead of `vaadin-avatar`.

In `vaadin-message-input`:
- Define `vaadin-message-input-text-area` and use it instead of `vaadin-text-area`.
- Define `vaadin-message-input-button` and use it instead of `vaadin-button`.

[See for example the `<vaadin-text-field>` inside `<vaadin-date-picker>`](
https://github.com/vaadin/vaadin-date-picker/blob/ba6c8be0bc1050d87f05326ae00502d609daa2ff/src/vaadin-date-picker-text-field.js#L41-L47).

**Comment by tomivirkki** [comment]
The main purpose of this is themeability. There have been cases where users have wanted to style all the text fields inside date pickers without affecting the other text fields on the app. With this approach, the user can make a style module target the extension tag name directly and the additional styles will only end up in the template of the extension.

Another important reason is related to when a component that wraps, let's say, a `<vaadin-text-field>`, needs to add some styles on top of the built-in `<vaadin-text-field>` styles. If it uses a style module targeting "vaadin-text-field" for this purpose, the styles might get registered too late in case `<vaadin-text-field>` was already defined/finalized somewhere else (on another view or by some other component that wraps a text field). This would result in the custom styles getting or not getting applied to the wrapped `<vaadin-text-field>`, depending on the import order.

**Comment by tomivirkki** [comment]
Same applies to `vaadin-text-area` and `vaadin-button` inside the newly added `vaadin-message-input` -element

**Comment by pekam** [comment]
The ticket is now updated to cover also text area and button.
