### ISSUE TITLE
Flow: MessageInput

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-messages#30]
```java
class MessageInput {
  String getValue();
  void setValue(String);

  Registration addSubmitListener(ComponentEventListener<SubmitEvent>);
}
```

```java
class SubmitEvent extends ComponentEvent {
  String getValue();
}
```

**Comment by pekam** [comment]
I18n split to another ticket #37

**Comment by heruan** [comment]
Do we need a programmatic `submit()` method?

**Comment by Peppe** [comment]
I do not think so. The web component has a private `submit()` for internal purposes, but it is not public API.

**Comment by pekam** [comment]
Resolved in https://github.com/vaadin/vaadin-flow-components/pull/658
