### ISSUE TITLE
vaadin-message-input i18n

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-messages#33]
Add `i18n` property to `vaadin-message-input`, with the following default value:
```js
i18n: {
  send: "Send",
  message: "Message"
}
```
`i18n.send` should be used as the text content of the button.
`i18n.message` should be used as the text area's placeholder and aria-label.

**Comment by jouni** [comment]
Just wondering, do we want to keep introducing this same API to new components, when we already know that we want to eventually move away from it in existing components? Which is the lesser even – more debt to pay eventually, or inconsistent APIs in the meanwhile (with possibly an improved API in the newer components)?

**Comment by pekam** [comment]
I'm not aware of these plans, but personally I think consistency is more important and it's better to update all the components at once. Especially if there's a chance that the new API design might still change.
